add movie screen
camilarsi/the-movie-db-app pull request #1
Opened 2023-08-24 13:47 UTC by camilarsi

<img width="200" alt="image" src="https://github.com/camilarsi/the-movie-db-app/assets/70240658/b5b4ce1f-f3f9-412a-a79b-7a1c21600c46">
<img width="200" alt="image" src="https://github.com/camilarsi/the-movie-db-app/assets/70240658/76a448c3-2c8d-4ae0-b515-9400b36a09a6">

2023-08-24 13:51 UTC, LeonardoMolleker commented on lib/constants.dart
> +      Padding(padding: EdgeInsets.symmetric(vertical: 3, horizontal: 8));
trailing comma

2023-08-24 13:51 UTC, LeonardoMolleker commented on lib/custom_icon_button.dart
> +      {super.key, required this.icon, required this.color, this.onPressed});
comma

2023-08-24 13:51 UTC, LeonardoMolleker commented on lib/custom_icon_button.dart
> +            offset: Offset(0, 1),
constant

2023-08-24 13:51 UTC, LeonardoMolleker commented on lib/custom_icon_button.dart
> +            blurRadius: 2,
constant

2023-08-24 13:52 UTC, LeonardoMolleker commented on lib/custom_icon_button.dart
> +      iconSize: 35,
constant

2023-08-24 13:52 UTC, LeonardoMolleker commented on lib/fixed_search_bar.dart
> +      top: 0,
constant

2023-08-24 13:52 UTC, LeonardoMolleker commented on lib/fixed_search_bar.dart
> +        height: 125,
constant

2023-08-24 13:52 UTC, LeonardoMolleker commented on lib/fixed_search_bar.dart
> +                colors: [Colors.black54, Colors.transparent],
comma

2023-08-24 13:52 UTC, LeonardoMolleker commented on lib/fixed_search_bar.dart
> +          elevation: 0,
constant

2023-08-24 13:52 UTC, LeonardoMolleker commented on lib/fixed_search_bar.dart
> +              iconSize: 35,
constant

2023-08-24 13:52 UTC, LeonardoMolleker commented on lib/genre_container.dart
> +  const GenreContainer({super.key, required this.genre});
comma

2023-08-24 13:52 UTC, LeonardoMolleker commented on lib/genre_container.dart
> +      padding: const EdgeInsets.symmetric(vertical: 3, horizontal: 8),
constants and trailing comma

2023-08-24 13:52 UTC, LeonardoMolleker commented on lib/genre_container.dart
> +        color: Colors.grey.withOpacity(0.4),
constant

2023-08-24 13:52 UTC, LeonardoMolleker commented on lib/genre_container.dart
> +        borderRadius: BorderRadius.circular(10),
constant

2023-08-24 13:53 UTC, LeonardoMolleker commented on lib/genre_container.dart
> +              offset: Offset(0, 1),
constant

2023-08-24 13:53 UTC, LeonardoMolleker commented on lib/genre_container.dart
> +          fontSize: 14,
constant

2023-08-24 13:53 UTC, LeonardoMolleker commented on lib/genre_container.dart
> +              blurRadius: 2,
constant

2023-08-24 13:54 UTC, LeonardoMolleker commented on lib/interactive_aside_bar.dart
> +      right: 0,
constants

2023-08-24 13:54 UTC, LeonardoMolleker commented on lib/interactive_aside_bar.dart
> +                    })),
trailing coma

2023-08-24 13:54 UTC, LeonardoMolleker commented on lib/interactive_aside_bar.dart
> +                color: like ? Colors.redAccent.withOpacity(0.9) : iconColor,
constant

2023-08-24 13:55 UTC, LeonardoMolleker commented on lib/interactive_aside_bar.dart
> +            Text(views, style: Constants.interactiveAsideBarTextStyle),
trailing commas in the texts and looks like you can abstract it

2023-08-24 13:55 UTC, LeonardoMolleker commented on lib/main.dart
> +            })),
commas

2023-08-24 13:55 UTC, LeonardoMolleker commented on lib/main.dart
> +                      child: MovieInformation(movie: movie)),
comma

2023-08-24 13:55 UTC, LeonardoMolleker commented on lib/main.dart
> +            right: true,
all these parameters are tru by default so they are unnecesary

2023-08-24 13:55 UTC, LeonardoMolleker commented on lib/main.dart
> +      title: "the movie db app",
constant

2023-08-24 13:55 UTC, LeonardoMolleker commented on lib/main.dart
> +                      bottom: 0,
constant

2023-08-24 13:56 UTC, LeonardoMolleker commented on lib/mocks.dart
> +class MoviesMock {
let's make a constructor that returns this mocked movie

2023-08-24 13:56 UTC, LeonardoMolleker commented on lib/movie.dart
> +      required this.genres});
comma

2023-08-24 13:56 UTC, LeonardoMolleker commented on lib/movie_details.dart
> +      required this.releaseDate});
comma

2023-08-24 13:57 UTC, LeonardoMolleker commented on lib/movie_details.dart
> +            Text('more...', style: textStyleMoreButton),
constant

2023-08-24 13:57 UTC, LeonardoMolleker commented on lib/movie_information.dart
> +          right: MediaQuery.of(context).size.width * 0.1, top: 90),
constants and comma

2023-08-24 13:57 UTC, LeonardoMolleker commented on lib/movie_information.dart
> +            padding: const EdgeInsets.symmetric(horizontal: 10),
constant

2023-08-24 13:57 UTC, LeonardoMolleker commented on lib/movie_information.dart
> +            padding: const EdgeInsets.only(bottom: 10),
constant

2023-08-24 13:58 UTC, LeonardoMolleker commented on lib/poster_background.dart
> +                  'assets/images/super_mario_bros._movie_poster.jpg'),
constant and comma

2023-08-24 13:58 UTC, LeonardoMolleker commented on lib/poster_background.dart
> +  const PosterBackground(this.url, {super.key});
comma

2023-08-24 13:58 UTC, LeonardoMolleker requested changes
Removed hardcoded code, add trailing commas, format the code and abstract some widgets

2023-08-24 19:39 UTC, Kevin-Guillen commented on lib/movie_details_row_more_button.dart
> +class MovieDetailsRowMoreButton extends StatelessWidget {
We could name this class just 'MoreButton' in the case that in the future you want to use the widget in other screens apart from the detail page.

2023-08-24 19:41 UTC, Kevin-Guillen commented on lib/movie_details_row_more_button.dart
> +        Text('more...', style: Constants.movieDetailsMoreButtonTextStyle),
Constant

2023-08-24 19:45 UTC, Kevin-Guillen commented on lib/poster_background.dart
> +        'assets/images/super_mario_bros._movie_poster.jpg';
lets move this const outside the build

2023-08-24 19:50 UTC, Kevin-Guillen commented on lib/movie_information.dart
> +    const double columnSecondPaddingEdgeOnlyBottom = 10;
lets move this constants outside the build method

2023-08-24 21:08 UTC, matiasilveiro-gl reviewed
Please try to leave the `build()` method as clean as possible, because it's called very often! I mean, if you need to create some instance there for any reason, go ahead. But for constants, it's better to have them as `static const` on top of the class, improving code readability as well

2023-08-24 21:08 UTC, matiasilveiro-gl commented on lib/constants.dart
> +abstract class Constants {
I'd rename this as `UiConstants` to improve readability

2023-08-24 21:08 UTC, matiasilveiro-gl commented on lib/custom_icon_button.dart
> +    const customIconButtonShadow = Constants.standardShadow;
Move these consts outside build method! Also they can be declared as `static const` outside

2023-08-24 21:08 UTC, matiasilveiro-gl commented on lib/custom_icon_button.dart
> +    const customIconButtonShadow = Constants.standardShadow;
What's more, the size could be a widget parameter with a default value of 35 in your case

2023-08-24 21:08 UTC, matiasilveiro-gl commented on lib/genre_container.dart
> +    const double textStyleFontSize = 14;
Move these outside the build method!

2023-08-24 21:08 UTC, matiasilveiro-gl commented on lib/helpers/big_number.dart
> +  }
This could be a property getter:
`int get number => _number;`

2023-08-24 21:08 UTC, matiasilveiro-gl commented on lib/interactive_aside_bar.dart
> +import 'package:the_movie_db_app/interactive_aside_bar_texts.dart';
Relative imports!

2023-08-24 21:08 UTC, matiasilveiro-gl commented on lib/interactive_aside_bar.dart
> +    const double customIconButtonColorOpacity = 0.9;
Move outside the build method too!

2023-08-24 21:08 UTC, matiasilveiro-gl commented on lib/main.dart
> +          ),
I'd extract this as a separate view, as you're gonna need that in the future!

2023-08-24 21:08 UTC, matiasilveiro-gl commented on lib/movie_details.dart
> +    );
Move outside of the build method!

2023-08-25 21:14 UTC, FranciscoGaraventa commented on lib/custom_icon_button.dart
> +      icon: Icon(icon, color: color, shadows: const [customIconButtonShadow]),
trailing comma

2023-08-25 21:14 UTC, FranciscoGaraventa commented on lib/fixed_search_bar.dart
> +    const double iconButtonSize = 35;
Try to define all the const outside the build method

2023-08-25 21:16 UTC, FranciscoGaraventa commented on lib/interactive_aside_bar.dart
> +                  like = like ? false : true;
This validation is not necessery, you can directly assign like the opposite value like
like = !like

2023-08-25 21:16 UTC, FranciscoGaraventa commented on lib/main.dart
> +          positionedBottom: positionedBottom, movie: movie),
trailing comma

2023-08-25 21:16 UTC, FranciscoGaraventa commented on lib/movie.dart
> +    genres = ['Animation', 'Family', 'Adventure', 'Fantasy', 'Comedy'];
trailing comma

2023-08-25 21:19 UTC, FranciscoGaraventa commented on lib/movie.dart
> +  Movie.superMario() {
You can made an factory method that return a mock movie, also you can renamed like mockMovie, is more generic and also in the future if i don't want to use anymore a mario movie an instead i want to use a harry potter movie this constructor would stop using it and would have to create a similar one that is Movie.harryPotter

2023-08-25 21:19 UTC, FranciscoGaraventa commented on lib/movie_info_outer_layout.dart
> +          builder: (BuildContext context, BoxConstraints constrains) {
trailing comma

2023-08-25 21:20 UTC, FranciscoGaraventa commented on lib/poster_background.dart
> +                colors: [Colors.black, Colors.transparent],
trailing comma

2023-08-25 21:20 UTC, FranciscoGaraventa commented on lib/poster_background.dart
> +          bottom: 75,
Add value to const

2023-08-28 01:11 UTC, camilarsi commented on lib/poster_background.dart
> +          bottom: 75,
done

2023-08-28 01:12 UTC, camilarsi commented on lib/poster_background.dart
> +                colors: [Colors.black, Colors.transparent],
done

2023-08-28 01:12 UTC, camilarsi commented on lib/movie_info_outer_layout.dart
> +          builder: (BuildContext context, BoxConstraints constrains) {
done

2023-08-28 01:12 UTC, camilarsi commented on lib/movie.dart
> +  Movie.superMario() {
done

2023-08-28 01:12 UTC, camilarsi commented on lib/movie.dart
> +    genres = ['Animation', 'Family', 'Adventure', 'Fantasy', 'Comedy'];
done

2023-08-28 01:12 UTC, camilarsi commented on lib/main.dart
> +          positionedBottom: positionedBottom, movie: movie),
done

2023-08-28 01:12 UTC, camilarsi commented on lib/interactive_aside_bar.dart
> +                  like = like ? false : true;
done

2023-08-28 01:12 UTC, camilarsi commented on lib/fixed_search_bar.dart
> +    const double iconButtonSize = 35;
done

2023-08-28 01:14 UTC, camilarsi commented
@LeonardoMolleker @Kevin-Guillen @matiasilveiro-gl  @FranciscoGaraventa all ready for review

2023-08-28 16:27 UTC, matiasilveiro-gl reviewed
Great refactor! A few new small comments:

2023-08-28 16:27 UTC, matiasilveiro-gl commented on lib/fixed_search_bar.dart
> +                icon: Icons.search, color: Colors.white, onPressed: null),
Trailing comma here, and autoformat!

2023-08-28 16:27 UTC, matiasilveiro-gl commented on lib/movie.dart
> +        ]);
Trailing comma and autoformat

2023-08-28 16:27 UTC, matiasilveiro-gl commented on lib/movie_info_outer_layout.dart
> +                    url: 'assets/images/super_mario_bros._movie_poster.jpg'),
This URL should come from the movie class

2023-08-28 16:27 UTC, matiasilveiro-gl commented on lib/movie_information.dart
Some missing trailing commas in this file

2023-08-28 18:07 UTC, Kevin-Guillen requested changes
We could start from now organizing the files in different folders

2023-08-28 19:51 UTC, camilarsi commented
@Kevin-Guillen directory refactor done

2023-08-29 18:46 UTC, matiasilveiro-gl approved these changes
LGTM! Just minor comments

2023-08-29 18:46 UTC, matiasilveiro-gl commented on lib/movie/movie.dart
I'd rename the folder as `models`

2023-08-29 18:46 UTC, matiasilveiro-gl commented on lib/widgets/interactive_aside_bar.dart
> +  String views = BigNumber(20456).getShortString();
I know this was for the sake of the demo, but consider either receiving them as parameters or adding a `// TODO` comment to change that in the future

2023-08-29 18:49 UTC, LeonardoMolleker commented on lib/widgets/poster_background.dart
> +          bottom: 75,
constant

2023-08-29 18:50 UTC, LeonardoMolleker commented on lib/widgets/movie_details.dart
> +          moreButtonTextContent: 'more...',
constant

2023-08-29 18:50 UTC, LeonardoMolleker commented on lib/widgets/movie_details.dart
> +                  movieDetailsTextStyle.copyWith(fontWeight: FontWeight.bold),
trailing comma

2023-08-29 18:51 UTC, LeonardoMolleker commented on lib/widgets/movie_details.dart
> +        offset: Offset(textStyleShadowOffsetX, textStyleShadowOffsetY),
trailing comma

2023-08-30 18:24 UTC, Kevin-Guillen approved these changes
LGTM

2023-08-31 11:37 UTC, FranciscoGaraventa approved these changes
LG

2023-08-31 17:28 UTC, LeonardoMolleker approved these changes

2023-08-31 18:06 UTC, merged