Camila.silva/modulo 5
camilarsi/the-movie-db-app pull request #4
Opened 2023-10-20 13:26 UTC by camilarsi

https://github.com/camilarsi/the-movie-db-app/assets/70240658/ebc031fb-be2c-4875-ac32-c60c007f9e95

2023-10-26 13:03 UTC, matiasilveiro-gl commented on lib/src/config/route/routes_generator.dart
> +        if (args is Genre) {
`else`? You can either throw an exception or show an error screen for the developer.
(Non-blocker comment 😊 )

2023-10-26 13:03 UTC, matiasilveiro-gl commented on lib/src/core/util/ui_constants.dart
> +  ];
Minor, not blocker!
You could create an `enum` for this, wrapping both the title and the path values:
```dart
enum MovieSection {
  nowPlaying('Now Playing', 'now_playing'),
  popular('Popular', 'popular'),
  ...;

  const MovieSection(this.title, this.path);
  final String title;
  final String path;
}
```
And then use `MovieSection.values` to access the list of possible values.

2023-10-26 13:03 UTC, matiasilveiro-gl commented on lib/src/domain/useCase/display_genres_list.dart
> +  late final RemoteGenresListRepository repository =
Why marking this as `late`? Also, you could receive this repository as a parameter, so as to be able to unit test this usecase!

2023-10-26 13:03 UTC, matiasilveiro-gl commented on lib/src/data/repository/remote_movies_list_repository.dart
> +    required this.category,
This could be a parameter of the `fetchMoviesList` method! So that your repository object doesn't depend on the data path

2023-10-26 13:03 UTC, matiasilveiro-gl commented on lib/src/domain/useCase/display_movie_detail_.dart
> +      RemoteMovieDetailRepository(movieId: movieId);
Why does the repository need the `movieId` to be created if later you pass that as a method parameter?

2023-10-26 13:03 UTC, matiasilveiro-gl commented on lib/src/domain/useCase/display_movies_list_from_category.dart
> +  );
Same as before. This parameter should be for the method call instead!

2023-10-26 13:03 UTC, matiasilveiro-gl commented on lib/src/presentation/bloc/custom_drawer_bloc.dart
> +  final DisplayGenresList displayGenresList = DisplayGenresList();
You could receive this as a constructor parameter to be able to unit test the bloc! 
You could do something like:
```dart
class CustomDrawerBloc extends ICustomDrawerBloc {
  final DisplayGenresList displayGenresList;
  CustomDrawerBloc({
    DisplayGenresList? displayGenresList
  }) : this.displayGenresList = displayGenresList ?? DisplayGenresList();
}
```
With that code you either receive the object as parameter, or create a default instance if not specified! Thus you can provide a mocked instance for unit testing.

2023-10-26 13:03 UTC, matiasilveiro-gl commented on lib/src/presentation/bloc/movies_grid_bloc.dart
> +  );
Same as before

2023-10-26 13:03 UTC, matiasilveiro-gl commented on lib/src/presentation/widget/custom_drawer/custom_drawer.dart
> +                                  '/moviesGridByGenre',
Use the route object from your AppRouter: `RouteGenerator. movieGridByGenre`

2023-10-26 13:44 UTC, MarcosCGlobant requested changes

2023-10-26 13:44 UTC, MarcosCGlobant commented on lib/src/data/repository/remote_movies_list_repository.dart
> +  //      Uri.parse('$baseUrl$'movie/$category'?api_key=$apiKey');
is this commented line needed

2023-10-26 13:44 UTC, MarcosCGlobant commented on lib/src/data/repository/remote_repository.dart
> +        (_) => 'Oops! Something went wrong'
this values should be save into constants

2023-10-26 13:44 UTC, MarcosCGlobant commented on lib/src/presentation/bloc/custom_drawer_bloc.dart
> +        genresListState.error = 'The response is empty';
save the hardcoded values into constants

2023-10-26 13:44 UTC, MarcosCGlobant commented on lib/src/presentation/bloc/movies_grid_bloc.dart
> +        moviesListState.error = 'The response is empty';
same as the other file, this are duplicated values, should be in a constants file and used from there

2023-10-26 13:44 UTC, MarcosCGlobant commented on lib/src/presentation/view/home.dart
> +                : 'TMDBApp',
move the hardcoded values into constants

2023-10-26 13:44 UTC, MarcosCGlobant commented on lib/src/presentation/widget/movies_grid/container_grid_view_item.dart
> +            '/movieDetails',
use the routes as Mati explained before

2023-10-30 20:48 UTC, matiasilveiro-gl commented on lib/src/core/util/ui_constants.dart
> +  ];
Now with the `MovieSection` you're good to delete this!

2023-10-30 20:48 UTC, matiasilveiro-gl commented on lib/src/presentation/bloc/movies_grid_bloc.dart
> +      DisplayMoviesListFromSection? displayMoviesListFromSection}) {
Trailing comma

2023-10-30 20:48 UTC, matiasilveiro-gl commented on lib/src/domain/useCase/display_movie_detail_.dart
> +  });
You'd need these parameters of the UseCases to be parameters of the methods instead of the objects, especially when moving to `Provider. It'd be way easier to provide these objects if the don't depend on these parameters (they're only used when calling the fetch method). But it's OK for now

2023-10-30 20:48 UTC, matiasilveiro-gl commented on test/unit/domain/repository/genre_repository_test.dart
> +      TestWidgetsFlutterBinding.ensureInitialized();
I think line 13 is not needed. Same for the rest of unit tests when no widgets are being tested

2023-10-30 20:48 UTC, matiasilveiro-gl commented on test/unit/data/repository/remote_repository_test.dart
> +class MockRemoteRepository<T> extends Mock implements RemoteRepository {
Testing the `RemoteRepository` class by testing a mock of it it's not correct.
The proper way would be to have the `Client` as a constructor parameter of the repository, and mock that client.

2023-10-31 12:25 UTC, FranciscoGaraventa commented on lib/src/data/repository/remote_repository.dart
> +  Future<DataState<T>> fetch(Function parseData, Uri uri) async {
trailing comma

2023-10-31 12:25 UTC, FranciscoGaraventa commented on lib/src/data/repository/remote_repository.dart
> +    if (response.statusCode == 200) {
Here you can use HttpStatus.OK to replace the 200 hardcoded

2023-10-31 12:26 UTC, FranciscoGaraventa commented on lib/src/domain/useCase/display_genres_list.dart
> +  late final Uri path = Uri.parse(
Do you really need to define this with late?

2023-10-31 12:28 UTC, FranciscoGaraventa commented on lib/src/presentation/widget/custom_drawer/custom_drawer.dart
> +        builder: (context, snapshot) {
Add type of the parameters and also you missed a trailing comma

2023-10-31 12:29 UTC, FranciscoGaraventa commented on lib/src/presentation/widget/movies_grid/container_grid_view_item.dart
> +  const ContainerGridViewItem({required this.movie, super.key});
trailing comma

2023-10-31 12:29 UTC, FranciscoGaraventa commented on lib/src/presentation/widget/movies_grid/movies_grid.dart
> +import 'package:the_movie_db_app/src/presentation/widget/movies_grid/stream_builder_movies_list.dart';
relative import

2023-10-31 12:30 UTC, FranciscoGaraventa commented on lib/src/presentation/widget/movies_grid/stream_builder_movies_list.dart
> +      builder: (context, snapshot) {
Add the parameter types and also the missing trailing comma

2023-10-31 13:07 UTC, MarcosCGlobant approved these changes

2023-11-01 12:41 UTC, matiasilveiro-gl approved these changes

2023-11-01 19:45 UTC, LeonardoMolleker commented on lib/src/config/route/routes_generator.dart
> +          throw Exception("Bad Request");
constant

2023-11-01 19:46 UTC, LeonardoMolleker commented on lib/src/core/bloc/i_movies_grid_bloc.dart
> +abstract class IMoviesGridBloc extends IBloc {}
delete this class if you don't need it

2023-11-01 19:47 UTC, LeonardoMolleker commented on lib/src/core/util/ui_constants.dart
> +enum MovieSection {
this should be in a new file, and trailing commas

2023-11-01 19:50 UTC, LeonardoMolleker commented on lib/src/data/repository/remote_repository.dart
> +    final response = await client.get(uri);
try throwing an exception here and see what happens without having a try catch bloc, the code works?

2023-11-01 19:55 UTC, LeonardoMolleker commented on lib/src/domain/useCase/display_movies_list_from_section.dart
> +  final String section;
The same as mati said above

2023-11-01 19:55 UTC, LeonardoMolleker commented on lib/src/domain/useCase/display_movies_list_from_section_by_genre.dart
> +  final Genre genre;
The same as mati said above

2023-11-02 19:44 UTC, Kevin-Guillen approved these changes

2023-11-03 15:24 UTC, FranciscoGaraventa approved these changes

2023-11-03 19:59 UTC, merged